# Generated by Django 3.1.7 on 2021-05-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('kilocalories', models.IntegerField()),
                ('carbohydrates', models.FloatField()),
                ('fats', models.FloatField()),
                ('proteins', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('energy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.foodenergy')),
            ],
        ),
    ]
