# Generated by Django 3.1.7 on 2021-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210530_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
